name: starfish-sensortag-app 
version: '0.2' 
#list of architectures the snap may run on. Defaults to [all].
#architectures: 
#	- all | amd64 | i386 | armhf
architectures: [ all ]
summary: SSN Starfish Data Platform example using BLE SensorTag
description: |
      Fetch TI BLE CC2650 SensorTag data and post it to SSN Starfish Data Platform
grade:  devel
confinement: devmode

apps:
  run:
    command: bin/nodeapp
    plugs: [bluetooth-control, network-bind, network]
#  hciconfig:
#    command: usr/bin/hciconfig
#    plugs: [  bluetooth-control ]
  hcitool:
    command: usr/bin/hcitool
    plugs: [ bluetooth-control ]
  bluetoothctl:
    command: usr/bin/bluetoothctl
    plugs: [ client ]
  bluez:
    command: "usr/lib/bluetooth/bluetoothd -E"
    daemon: simple
    slots: [ service ]

plugs:
  client:
      interface: bluez

slots:
  service:
      interface: bluez

parts:
  starfish-sdk-wrapper:
    source: .
    plugin: nodejs
    node-packages: 
      - request-promise-native
      - inotify
      - jsonwebtoken
      - request@^2.34
#!dh getting unmet dependancy error

  bluez:
    plugin: nil
    stage-packages:
      - bluez

  bluepy:
    plugin: python
    source: bluepy
    build-packages: [libglib2.0-dev]
      
  move:
     plugin: dump
     source: bin
     organize:
       sensortagUpdate: bin/sensortagUpdate  

